export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';
export const FETCH_PHOTOS_END = 'FETCH_PHOTOS_END';

export const SHOW_PHOTO = 'SHOW_PHOTO';
export const SHOW_NEXT_PHOTO = 'SHOW_NEXT_PHOTO';
export const SHOW_PREV_PHOTO = 'SHOW_PREV_PHOTO';
export const HIDE_PHOTO = 'HIDE_PHOTO';
